name: voxguard
description: "VoxGuard - Real-time AI Call Screening, Deepfake Voice Detection & Dynamic Risk Engine"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^3.0.1
  http: ^1.2.2
  provider: ^6.1.2
  intl: ^0.19.0
  flutter_overlay_window: ^0.4.5
  permission_handler: ^11.3.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
